const pinkPokeball = 'images/pink_pokeball.png';
const pikachuRunning = 'images/loading.gif';
const sadPikachu = 'images/sad_pikachu.png';
const imageUrl = '';
const loadingText = 'Loading...';
const appTItle = 'Pokedex - Daniel Alvarez';
const tryAgainText = 'Please try again later...';
const tryNowText = 'Try again now';
const errorText = 'Something went wrong';
